# Generated by Django 4.0.4 on 2022-05-21 06:31

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservationapp', '0002_bus_feedback_province_schedule_station_tag_ticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='schedule',
            name='check departure_time is greater than now',
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('HOLIDAY', 'Holiday'), ('TET', 'Tet')], default='NORMAL', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(check=models.Q(('departure_time__gte', datetime.datetime(2022, 5, 21, 6, 31, 21, 671980, tzinfo=utc))), name='check departure_time is greater than now'),
        ),
        migrations.AddField(
            model_name='bus',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='reservationapp.organization'),
        ),
    ]
