# Generated by Django 4.0.4 on 2022-05-21 10:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservationapp', '0003_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('liked', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='schedule',
            name='check departure_time is greater than now',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservationapp.bus'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('HOLIDAY', 'Holiday'), ('TET', 'Tet')], default='NORMAL', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(check=models.Q(('departure_time__gte', datetime.datetime(2022, 5, 21, 10, 21, 46, 166570, tzinfo=utc))), name='check departure_time is greater than now'),
        ),
        migrations.AddField(
            model_name='like',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservationapp.bus'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'bus')},
        ),
    ]
