# Generated by Django 4.0.4 on 2022-05-21 10:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservationapp', '0004_like_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedule',
            name='check departure_time is greater than now',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='reservationapp.bus'),
        ),
        migrations.AlterField(
            model_name='like',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('HOLIDAY', 'Holiday'), ('TET', 'Tet')], default='NORMAL', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(check=models.Q(('departure_time__gte', datetime.datetime(2022, 5, 21, 10, 51, 39, 42027, tzinfo=utc))), name='check departure_time is greater than now'),
        ),
        migrations.RemoveField(
            model_name='like',
            name='liked',
        ),
    ]
